spring: 
    profiles: 
        active: dev
        
---
spring: 
    profiles:dev  # 开发环境
    application: 
        name: microservicecloud-config-atguigu-dev
        
---
pring: 
    profiles:test  # 开发环境
    application: 
        name: microservicecloud-config-atguigu-test